#!/bin/bash

#########################################################

# NOTE: Get it from gitlab
PRIVATE_TOKEN='[YOUR PRIVATE TOKEN]'

# NOTE: Get it from your project's setting page
PROJECT_ID='[YOUR PROJECT ID]'

# NOTE: URL should start from `[https|http]://`
# It should be like `https://gitlab.com`
PROJECT_BASE_URL='[YOUR PROJECT BASE URL]'

# NOTE: Directory should be `my-project/product1`
PROJECT_DIRECTORY='[YOUR PROJECT DIRECTORY]'

# It should be `httsp://gitlab.com/my-project/product1`
PROJECT_URL="${PROJECT_BASE_URL}/${PROJECT_DIRECTORY}"

# Set your fav browser
BROWSER='Google Chrome'

#########################################################

# NOTE: Set your commit hash as arg
COMMIT_HASH=$1

#########################################################

# Open MR page associated with a commit hash on the browser
# @param $1 commit hash
main() {

    # Get response from commit hash
    curl_response=$(curl -s --request GET --header "PRIVATE-TOKEN: ${PRIVATE_TOKEN}" ${PROJECT_BASE_URL}/api/v4/projects/${PROJECT_ID}/repository/commits/${COMMIT_HASH}/merge_requests)

    # Convert response into json format
    response_json=$(echo "${curl_response}" | cut -c 2- | rev | cut -c 2- | rev)

    # Get MR's id
    mr_id=$(echo "${response_json}" | jq -r '.iid')

    # Open MR page
    open -a "${BROWSER}" ${PROJECT_URL}/merge_requests/${mr_id}
}

[[ "${BASH_SOURCE[0]}" == "$0" ]] && main "$@"
